name: Docker Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - 'master'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_BUILDX_VERSION: "v0.10.3"
  PYTHON_VERSION: "3.11"
  
jobs:
  build-and-push-docker-image:
    name: Build and push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker # Can't be run with default docker-container due to buildx context
          version: ${{ env.DOCKER_BUILDX_VERSION }}
          install: true

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      
      - name: Get current date
        id: currentdate
        run: |
          echo "datetime=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
      
      - name: Build and Push Pull Request
        id: build-and-push-pr
        uses: docker/build-push-action@v2
        if: ${{ github.event_name == 'pull request' }}
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.head_ref }}_${{ env.datetime }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and Push Branch Not Master
        id: build-and-push-branch
        uses: docker/build-push-action@v2
        if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/master' }}
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}_${{ env.datetime }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and Push Master (latest image)
        id: build-and-push-latest
        uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}