name: Check Javascript style

on:
  push:
    branches: [ "dummy-dont-trigger" ]
  pull_request:
    branches: [ "dummy-dont-trigger" ]

  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  check-javascript-style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Upgrade yarn
        run: |
          yarn set version berry
          yarn set version 3

      - name: Install Node modules
        run: |
          cd web
          yarn install

      - name: Run the linter
        run: |
          cd web
          yarn run linter
